"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { BookOpen, Check, CircleHelp, Download, FileText, GraduationCap, LayoutDashboard, LibraryBig, Loader2, LogOut, MoreHorizontal, Plus, Search, Sparkles, Trash2, Upload, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { Progress } from "@/components/ui/progress";
import { toast } from "sonner";

type Question = { id: number; content: string; answer: string; analysis: string; subject: string; grade: string; type: string; difficulty: string; source: string; createdAt?: string };
type Draft = Omit<Question, "id">;
const seed: Question[] = [
  { id: -1, content: "如图，在 △ABC 中，AB = AC，∠A = 40°，求 ∠B 的度数。", answer: "70°", analysis: "等腰三角形两底角相等，∠B = (180° − 40°) ÷ 2 = 70°。", subject: "数学", grade: "九年级", type: "解答题", difficulty: "基础", source: "示例题库" },
  { id: -2, content: "已知函数 y = 2x + 1，当 x = 3 时，求 y 的值。", answer: "7", analysis: "将 x = 3 代入函数，y = 2 × 3 + 1 = 7。", subject: "数学", grade: "九年级", type: "填空题", difficulty: "基础", source: "示例题库" },
  { id: -3, content: "关于 x 的一元二次方程 x² − 5x + 6 = 0 的两个根分别是多少？", answer: "x₁ = 2，x₂ = 3", analysis: "因式分解得 (x − 2)(x − 3) = 0。", subject: "数学", grade: "九年级", type: "解答题", difficulty: "中等", source: "示例题库" },
];
const emptyDraft: Draft = { content: "", answer: "", analysis: "", subject: "数学", grade: "九年级", type: "解答题", difficulty: "中等", source: "手动录入" };

export default function QuestionBank() {
  const [items, setItems] = useState<Question[]>(seed);
  const [selected, setSelected] = useState<number[]>([]);
  const [query, setQuery] = useState(""); const [subject, setSubject] = useState("全部学科"); const [difficulty, setDifficulty] = useState("全部难度");
  const [manualOpen, setManualOpen] = useState(false); const [importOpen, setImportOpen] = useState(false); const [exportOpen, setExportOpen] = useState(false);
  const [draft, setDraft] = useState<Draft>(emptyDraft); const [parsed, setParsed] = useState<Draft[]>([]); const [fileName, setFileName] = useState("");
  const [parsing, setParsing] = useState(false); const [saving, setSaving] = useState(false); const fileRef = useRef<HTMLInputElement>(null);

  useEffect(() => { fetch("/api/questions").then(r => r.ok ? r.json() : null).then(data => data?.questions?.length && setItems(data.questions)).catch(() => {}); }, []);
  const filtered = useMemo(() => items.filter(q => `${q.content} ${q.answer} ${q.source}`.toLowerCase().includes(query.toLowerCase()) && (subject === "全部学科" || q.subject === subject) && (difficulty === "全部难度" || q.difficulty === difficulty)), [items, query, subject, difficulty]);
  const toggle = (id: number) => setSelected(s => s.includes(id) ? s.filter(x => x !== id) : [...s, id]);
  const saveQuestions = async (questionsToSave: Draft[]) => {
    setSaving(true);
    try { const res = await fetch("/api/questions", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ questions: questionsToSave }) }); const data = await res.json(); if (!res.ok) throw new Error(data.error || "保存失败"); setItems(old => [...data.questions, ...old.filter(q => q.id > 0)]); toast.success(`已入库 ${data.questions.length} 道题目`); return true; }
    catch (error) { toast.error(error instanceof Error ? error.message : "保存失败"); return false; } finally { setSaving(false); }
  };
  const handlePdf = async (file?: File) => {
    if (!file) return; if (file.type !== "application/pdf" && !file.name.toLowerCase().endsWith(".pdf")) { toast.error("请选择 PDF 文件"); return; }
    setFileName(file.name); setParsing(true); setParsed([]);
    try { const pdfjs = await import("pdfjs-dist"); pdfjs.GlobalWorkerOptions.workerSrc = new URL("pdfjs-dist/build/pdf.worker.min.mjs", import.meta.url).toString(); const pdf = await pdfjs.getDocument({ data: await file.arrayBuffer() }).promise; const pages: string[] = [];
      for (let i = 1; i <= pdf.numPages; i++) { const page = await pdf.getPage(i); const text = await page.getTextContent(); pages.push(text.items.map(item => "str" in item ? item.str : "").join(" ")); }
      const raw = pages.join("\n").replace(/\s+/g, " ").trim(); if (!raw) throw new Error("未检测到可复制文字。这可能是扫描版 PDF，请先进行 OCR 后再上传。");
      const chunks = raw.split(/(?=(?:^|\s)(?:第\s*)?\d{1,3}[.、．)）]\s*)/).map(x => x.trim()).filter(x => x.length > 8); const list = (chunks.length > 1 ? chunks : [raw]).slice(0, 80);
      setParsed(list.map(content => ({ ...emptyDraft, content, source: file.name }))); toast.success(`识别完成，共发现 ${list.length} 道候选题目`);
    } catch (error) { toast.error(error instanceof Error ? error.message : "PDF 识别失败"); } finally { setParsing(false); }
  };
  const removeSelected = async () => { const realIds = selected.filter(id => id > 0); if (realIds.length) await fetch("/api/questions", { method: "DELETE", headers: { "content-type": "application/json" }, body: JSON.stringify({ ids: realIds }) }); setItems(old => old.filter(q => !selected.includes(q.id))); setSelected([]); toast.success("已删除所选题目"); };
  const exportPaper = (edition: "teacher" | "student") => { const chosen = items.filter(q => selected.includes(q.id)); const html = `<!doctype html><html><head><meta charset="utf-8"><title>${edition === "teacher" ? "教师版" : "学生版"}试卷</title><style>@page{size:A4;margin:20mm}body{font-family:"Microsoft YaHei",sans-serif;color:#172033;line-height:1.75}h1{text-align:center;margin:0}header{text-align:center;border-bottom:2px solid #172033;padding-bottom:18px;margin-bottom:26px}.meta{color:#667085;font-size:13px}.q{margin:22px 0;break-inside:avoid}.tag{font-size:12px;color:#52606d}.answer{margin-top:10px;background:#f3f6fb;border-left:3px solid #3157d5;padding:10px 14px}footer{margin-top:40px;text-align:center;color:#98a2b3;font-size:12px}</style></head><body><header><h1>阶段练习</h1><div class="meta">${edition === "teacher" ? "教师版 · 含参考答案与解析" : "学生版 · 姓名：__________　班级：__________"}</div></header>${chosen.map((q, i) => `<section class="q"><div><strong>${i + 1}.</strong> ${escapeHtml(q.content)}</div><div class="tag">${q.type} · ${q.difficulty}</div>${edition === "teacher" ? `<div class="answer"><strong>参考答案：</strong>${escapeHtml(q.answer || "暂无")}<br><strong>解析：</strong>${escapeHtml(q.analysis || "暂无")}</div>` : `<div style="height:72px;border-bottom:1px dashed #cbd5e1"></div>`}</section>`).join("")}<footer>共 ${chosen.length} 题 · 研题教研系统生成</footer><script>window.onload=()=>window.print()<\/script></body></html>`; const url = URL.createObjectURL(new Blob([html], { type: "text/html;charset=utf-8" })); const win = window.open(url, "_blank"); if (!win) toast.error("浏览器阻止了导出窗口，请允许弹窗后重试"); else { setExportOpen(false); setTimeout(() => URL.revokeObjectURL(url), 30000); } };

  return <div className="min-h-screen bg-[#f4f6fb] text-[#172033]">
    <aside className="fixed inset-y-0 left-0 z-20 hidden w-64 flex-col bg-[#12213f] text-white lg:flex"><div className="flex h-20 items-center gap-3 border-b border-white/10 px-7"><div className="grid h-10 w-10 place-items-center rounded-xl bg-[#ff8a34]"><BookOpen size={22}/></div><div><div className="text-xl font-bold tracking-wide">研题</div><div className="text-xs text-blue-200">教研题库系统</div></div></div><nav className="flex-1 space-y-2 p-4"><Side icon={<LayoutDashboard/>} label="工作台"/><Side icon={<LibraryBig/>} label="题库管理" active/><Side icon={<FileText/>} label="试卷中心"/><Side icon={<Sparkles/>} label="智能导题"/></nav><div className="border-t border-white/10 p-4"><div className="flex items-center gap-3 rounded-xl p-3"><div className="grid h-9 w-9 place-items-center rounded-full bg-blue-400 text-sm font-bold">杨</div><div className="min-w-0 flex-1"><div className="truncate text-sm font-semibold">教研老师</div><div className="text-xs text-blue-200">数学教研组</div></div><LogOut size={17} className="text-blue-200"/></div></div></aside>
    <main className="lg:ml-64"><header className="flex min-h-20 items-center justify-between gap-3 border-b border-slate-200 bg-white px-4 py-3 md:px-8"><div><h1 className="text-xl font-bold md:text-2xl">题库管理</h1><p className="hidden text-sm text-slate-500 sm:block">集中管理、整理与组卷</p></div><div className="flex gap-2"><Button variant="outline" className="rounded-xl" onClick={() => setImportOpen(true)}><Upload/> <span className="hidden sm:inline">PDF 智能导题</span></Button><Button className="rounded-xl bg-[#ff7a21] hover:bg-[#ed6812]" onClick={() => setManualOpen(true)}><Plus/> 添加题目</Button></div></header>
      <section className="p-4 md:p-8"><div className="mb-5 grid gap-3 sm:grid-cols-3"><Stat label="题目总数" value={items.length} unit="题" icon={<LibraryBig/>}/><Stat label="本次已选" value={selected.length} unit="题" icon={<Check/>}/><Stat label="覆盖学科" value={new Set(items.map(q=>q.subject)).size} unit="个" icon={<GraduationCap/>}/></div>
        <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-col gap-3 border-b border-slate-200 p-4 xl:flex-row xl:items-center"><div className="relative flex-1"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={18}/><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索题干、答案或来源…" className="h-11 rounded-xl border-slate-200 pl-10"/></div><div className="flex gap-2"><Filter value={subject} setValue={setSubject} options={["全部学科","数学","语文","英语","物理","化学"]}/><Filter value={difficulty} setValue={setDifficulty} options={["全部难度","基础","中等","困难"]}/></div><div className="ml-auto flex gap-2"><Button variant="outline" disabled={!selected.length} onClick={removeSelected} className="rounded-xl text-red-600"><Trash2/> 删除</Button><Button disabled={!selected.length} onClick={()=>setExportOpen(true)} className="rounded-xl bg-[#3157d5] hover:bg-[#2646b1]"><Download/> 导出试卷</Button></div></div>
          <div className="overflow-x-auto"><table className="w-full min-w-[920px] text-left"><thead className="bg-slate-50 text-sm text-slate-500"><tr><th className="w-14 p-4"><Checkbox checked={filtered.length>0&&filtered.every(q=>selected.includes(q.id))} onCheckedChange={()=>setSelected(filtered.every(q=>selected.includes(q.id))?selected.filter(id=>!filtered.some(q=>q.id===id)):[...new Set([...selected,...filtered.map(q=>q.id)])])}/></th><th className="p-4 font-medium">题目内容</th><th className="w-24 p-4 font-medium">题型</th><th className="w-24 p-4 font-medium">难度</th><th className="w-28 p-4 font-medium">年级</th><th className="w-36 p-4 font-medium">来源</th><th className="w-14 p-4"/></tr></thead><tbody>{filtered.map(q=><tr key={q.id} className="border-t border-slate-100 align-top transition hover:bg-blue-50/40"><td className="p-4"><Checkbox checked={selected.includes(q.id)} onCheckedChange={()=>toggle(q.id)}/></td><td className="max-w-2xl p-4"><div className="line-clamp-2 font-medium leading-6">{q.content}</div><div className="mt-2 text-xs text-slate-400">{q.subject} · {q.answer ? `答案：${q.answer}` : "暂未录入答案"}</div></td><td className="p-4"><span className="rounded-md bg-blue-50 px-2 py-1 text-xs text-blue-700">{q.type}</span></td><td className="p-4"><Difficulty value={q.difficulty}/></td><td className="p-4 text-sm text-slate-600">{q.grade}</td><td className="p-4 text-sm text-slate-500"><span className="line-clamp-2">{q.source}</span></td><td className="p-4"><Button variant="ghost" size="icon"><MoreHorizontal/></Button></td></tr>)}</tbody></table></div>
          {!filtered.length&&<div className="grid place-items-center py-20 text-center"><CircleHelp size={38} className="mb-3 text-slate-300"/><p className="font-medium">没有找到符合条件的题目</p><p className="mt-1 text-sm text-slate-400">试试更换筛选条件或添加新题目</p></div>}<div className="flex items-center justify-between border-t border-slate-100 px-5 py-4 text-sm text-slate-500"><span>共 {filtered.length} 道题目</span><span>已选择 {selected.length} 道</span></div></div></section></main>

    <Dialog open={manualOpen} onOpenChange={setManualOpen}><DialogContent className="max-h-[92vh] overflow-y-auto sm:max-w-2xl"><DialogHeader><DialogTitle>添加题目</DialogTitle><DialogDescription>录入题干、答案和解析，保存后进入题库。</DialogDescription></DialogHeader><QuestionForm draft={draft} setDraft={setDraft}/><DialogFooter><Button variant="outline" onClick={()=>setManualOpen(false)}>取消</Button><Button disabled={!draft.content.trim()||saving} onClick={async()=>{if(await saveQuestions([draft])){setManualOpen(false);setDraft(emptyDraft)}}} className="bg-[#3157d5]">{saving&&<Loader2 className="animate-spin"/>} 保存入库</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={importOpen} onOpenChange={setImportOpen}><DialogContent className="max-h-[92vh] overflow-y-auto sm:max-w-3xl"><DialogHeader><DialogTitle>PDF 智能导题</DialogTitle><DialogDescription>系统会提取 PDF 文字并按题号拆分，入库前可逐题校对。</DialogDescription></DialogHeader>{!parsed.length?<div onClick={()=>fileRef.current?.click()} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();void handlePdf(e.dataTransfer.files[0])}} className="cursor-pointer rounded-2xl border-2 border-dashed border-blue-200 bg-blue-50/50 px-6 py-14 text-center transition hover:border-blue-400"><input ref={fileRef} type="file" accept="application/pdf,.pdf" className="hidden" onChange={e=>void handlePdf(e.target.files?.[0])}/>{parsing?<><Loader2 className="mx-auto mb-4 animate-spin text-blue-600" size={38}/><p className="font-semibold">正在识别 {fileName}</p><Progress value={66} className="mx-auto mt-4 max-w-xs"/></>:<><div className="mx-auto mb-4 grid h-14 w-14 place-items-center rounded-2xl bg-white text-blue-600 shadow-sm"><Upload/></div><p className="font-semibold">点击选择或拖入 PDF 文件</p><p className="mt-2 text-sm text-slate-500">支持文字型 PDF，单次最多识别 80 道题目</p></>}</div>:<div className="space-y-3"><div className="flex items-center justify-between rounded-xl bg-emerald-50 p-4 text-emerald-800"><div className="flex items-center gap-2"><Check size={18}/><span className="font-medium">{fileName} · 已识别 {parsed.length} 道候选题</span></div><Button variant="ghost" size="sm" onClick={()=>setParsed([])}><X/></Button></div>{parsed.map((q,i)=><div key={i} className="rounded-xl border border-slate-200 p-3"><div className="mb-2 text-xs font-semibold text-blue-600">第 {i+1} 题</div><Textarea value={q.content} onChange={e=>setParsed(p=>p.map((x,j)=>j===i?{...x,content:e.target.value}:x))} className="min-h-20"/><div className="mt-2 grid gap-2 sm:grid-cols-2"><Input placeholder="参考答案（可稍后补充）" value={q.answer} onChange={e=>setParsed(p=>p.map((x,j)=>j===i?{...x,answer:e.target.value}:x))}/><Select value={q.type} onValueChange={v=>setParsed(p=>p.map((x,j)=>j===i?{...x,type:v}:x))}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{["选择题","填空题","判断题","解答题"].map(v=><SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select></div></div>)}</div>}<DialogFooter>{parsed.length>0&&<Button variant="outline" onClick={()=>setParsed([])}>重新选择</Button>}<Button disabled={!parsed.length||saving} onClick={async()=>{if(await saveQuestions(parsed)){setImportOpen(false);setParsed([]);setFileName("")}}} className="bg-[#3157d5]">{saving&&<Loader2 className="animate-spin"/>} 确认入库 {parsed.length||""}</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={exportOpen} onOpenChange={setExportOpen}><DialogContent><DialogHeader><DialogTitle>选择导出版本</DialogTitle><DialogDescription>已选择 {selected.length} 道题，导出后可打印或另存为 PDF。</DialogDescription></DialogHeader><div className="grid gap-3 sm:grid-cols-2"><Edition icon={<GraduationCap/>} title="教师版" desc="包含参考答案和详细解析" color="blue" onClick={()=>exportPaper("teacher")}/><Edition icon={<FileText/>} title="学生版" desc="隐藏答案，保留答题空间" color="orange" onClick={()=>exportPaper("student")}/></div></DialogContent></Dialog>
  </div>;
}

function escapeHtml(text:string){return text.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]||c))}
function Side({icon,label,active=false}:{icon:React.ReactNode;label:string;active?:boolean}){return <div className={`flex items-center gap-3 rounded-xl px-4 py-3 text-sm font-medium ${active?"bg-white/12 text-white":"text-blue-100 hover:bg-white/5"}`}><span className={active?"text-[#ff9a52]":""}>{icon}</span>{label}{active&&<span className="ml-auto h-2 w-2 rounded-full bg-[#ff8a34]"/>}</div>}
function Stat({label,value,unit,icon}:{label:string;value:number;unit:string;icon:React.ReactNode}){return <div className="flex items-center gap-4 rounded-2xl border border-slate-200 bg-white p-5"><div className="grid h-11 w-11 place-items-center rounded-xl bg-blue-50 text-[#3157d5]">{icon}</div><div><div className="text-sm text-slate-500">{label}</div><div className="mt-1 text-2xl font-bold">{value}<span className="ml-1 text-sm font-normal text-slate-400">{unit}</span></div></div></div>}
function Filter({value,setValue,options}:{value:string;setValue:(v:string)=>void;options:string[]}){return <Select value={value} onValueChange={setValue}><SelectTrigger className="h-11 min-w-32 rounded-xl"><SelectValue/></SelectTrigger><SelectContent>{options.map(v=><SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select>}
function Difficulty({value}:{value:string}){const cls=value==="困难"?"bg-red-50 text-red-700":value==="基础"?"bg-emerald-50 text-emerald-700":"bg-amber-50 text-amber-700";return <span className={`rounded-full px-2 py-1 text-xs ${cls}`}>{value}</span>}
function Edition({icon,title,desc,color,onClick}:{icon:React.ReactNode;title:string;desc:string;color:"blue"|"orange";onClick:()=>void}){return <button onClick={onClick} className={`rounded-2xl border-2 p-5 text-left transition hover:-translate-y-0.5 hover:shadow-md ${color==="blue"?"border-blue-100 hover:border-blue-400":"border-orange-100 hover:border-orange-400"}`}><div className={`mb-4 grid h-11 w-11 place-items-center rounded-xl ${color==="blue"?"bg-blue-50 text-blue-700":"bg-orange-50 text-orange-700"}`}>{icon}</div><div className="font-bold">{title}</div><div className="mt-1 text-sm text-slate-500">{desc}</div></button>}
function QuestionForm({draft,setDraft}:{draft:Draft;setDraft:(v:Draft)=>void}){const set=(key:keyof Draft,value:string)=>setDraft({...draft,[key]:value});return <div className="space-y-4 py-2"><div><Label>题目内容 *</Label><Textarea className="mt-2 min-h-28" placeholder="请输入完整题干…" value={draft.content} onChange={e=>set("content",e.target.value)}/></div><div className="grid gap-4 sm:grid-cols-2"><Field label="学科" value={draft.subject} setValue={v=>set("subject",v)} options={["数学","语文","英语","物理","化学"]}/><Field label="年级" value={draft.grade} setValue={v=>set("grade",v)} options={["七年级","八年级","九年级","高一","高二","高三"]}/><Field label="题型" value={draft.type} setValue={v=>set("type",v)} options={["选择题","填空题","判断题","解答题"]}/><Field label="难度" value={draft.difficulty} setValue={v=>set("difficulty",v)} options={["基础","中等","困难"]}/></div><div><Label>参考答案</Label><Textarea className="mt-2" placeholder="请输入参考答案…" value={draft.answer} onChange={e=>set("answer",e.target.value)}/></div><div><Label>题目解析</Label><Textarea className="mt-2" placeholder="请输入解题思路和步骤…" value={draft.analysis} onChange={e=>set("analysis",e.target.value)}/></div></div>}
function Field({label,value,setValue,options}:{label:string;value:string;setValue:(v:string)=>void;options:string[]}){return <div><Label>{label}</Label><Select value={value} onValueChange={setValue}><SelectTrigger className="mt-2 w-full"><SelectValue/></SelectTrigger><SelectContent>{options.map(v=><SelectItem value={v} key={v}>{v}</SelectItem>)}</SelectContent></Select></div>}
